adapp/urls.py
from django.urls import path

from . import views

app_name = "adapp"

urlpatterns = \
[
    path('', views.IndexView.as_view(), name="index"),
    path('addSqlData/', views.addSqlData, name="addSqlData"),
    path('analyseByCity/', views.analyseByCity, name="analyseByCity"),
    path('clearTables/', views.clearTables, name="clearTables"),
    path('sqldatabase/', views.SqlDatabaseView.as_view(), name="sqldatabase"),
]

barisdjmysql/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = \
[
    path('', include('adapp.urls')),
    path('admin/', admin.site.urls),
]

adapp/models.py
from django.db import models

# Django adds this default id if pk is not defined => id = models.AutoField(primary_key=True)

class Customer(models.Model):
    id = models.AutoField(primary_key=True) # Id (int)
    name = models.CharField(max_length=100, null=False, blank=False) # Ad (varchar)
    surname = models.CharField(max_length=100, null=False, blank=False) # Soyad (varchar)
    city = models.CharField(max_length=100, null=False, blank=False) # Sehir (varchar)

    def __str__(self):
        return "Customer's ID = " + str(self.id) + ", Name = " + self.name \
            + ", Surname = " + self.surname + ", City = " + self.city

class Basket(models.Model):
    id = models.AutoField(primary_key=True) # Id (int)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE) # MusteriId (int)

    def __str__(self):
        return "Basket's ID = " + str(self.id) + ", CustomerID = " + str(self.customer_id)

class BasketProduct(models.Model):
    id = models.AutoField(primary_key=True) # Id (int)
    basket = models.ForeignKey(Basket, on_delete=models.CASCADE) # SepetId (int)
    cost = models.DecimalField(max_digits=11, decimal_places=2, null=False) # Tutar (numeric)
    description = models.TextField(default="No description.") # Aciklama (varchar)

    def __str__(self):
        return "BasketProduct's ID = " + str(self.id) + ", BasketID = " + str(self.basket_id) \
            + ", Cost = " + str(self.cost) + ", Description = " + self.description

adapp/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Basket, BasketProduct, Customer
from .viewsHelper import createTestData, getBasketAndCostByCity, truncateTablesAndResetAutoIncrement

class IndexView(generic.TemplateView):
    template_name = 'adapp/index.html'

class SqlDatabaseView(generic.TemplateView):
    template_name = 'adapp/sqldatabase.html'

    def get_context_data(self, **kwargs):
         context = super(SqlDatabaseView, self).get_context_data(**kwargs)
         context['customerTable'] = Customer.objects.all().order_by("id")
         context['basketTable'] = Basket.objects.all().order_by("id")
         context['basketProductTable'] = BasketProduct.objects.all().order_by("id")
         return context

def addSqlData(request):
    customerCount = int(request.POST["customerCount"])
    basketCount = int(request.POST["basketCount"])
    createTestData(customerCount, basketCount)
    return HttpResponseRedirect(reverse('adapp:sqldatabase'))

def analyseByCity(request):
    getBasketAndCostByCity()
    return HttpResponseRedirect(reverse('adapp:index'))

def clearTables(request):
    truncateTablesAndResetAutoIncrement()
    return HttpResponseRedirect(reverse('adapp:sqldatabase'))

adapp/templates/adapp/index.html
<!DOCTYPE html>

<html>

<head>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'adapp/style.css' %}">
  <title>Ada yazilim assignment index html document</title>
</head>

<body>
  <h1 class="titleStyle">Ada yazilim assignment</h1>
  <div id="addSqlDataFormDiv">
    <form action="{% url 'adapp:addSqlData' %}" method="post" class="formStyle">
      {% csrf_token %}
      <div class="titleStyle">Add test data to database</div> <hr>
      <div class="formEleDiv">
        <label for="customerCount">Customer count:</label>
        <input type="number" min="1" placeholder="Enter customer count..." id="customerCount" name="customerCount" class="rightToLeft">
      </div>
      <div class="formEleDiv">
        <label for="basketCount">Basket count:</label>
        <input type="number" min="1" placeholder="Enter basket count..." id="basketCount" name="basketCount" class="rightToLeft">
      </div>
      <div class="formEleDiv">
        <input type="submit" value="Add" class="rightToLeft">
      </div>
    </form>
  </div>
  <div id="analyseByCityFormDiv">
    <form action="{% url 'adapp:analyseByCity' %}" method="post" class="formStyle">
      {% csrf_token %}
      <div class="titleStyle">Analyse by city</div> <hr>
      <div class="formEleDiv">
        <input type="submit" value="Analyse" class="rightToLeft">
      </div>
    </form>
  </div>
  <div>
    <a href="{% url 'adapp:sqldatabase' %}">Check database</a>
  </div>
</body>

</html>

adapp/templates/adapp/sqldatabase.html
<!DOCTYPE html>

<html>

<head>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'adapp/style.css' %}">
  <title>Ada yazilim assignment sqldatabase html document</title>
</head>

<body>
  <div>
    <a href="{% url 'adapp:index' %}">Go back to main page</a>
  </div>
  <div id="clearTablesFormDiv">
    <form action="{% url 'adapp:clearTables' %}" method="post" class="formStyle">
      {% csrf_token %}
      <div class="titleStyle">Clear tables</div> <hr>
      <div class="formEleDiv">
        <input type="submit" value="Clear" class="rightToLeft">
      </div>
    </form>
  </div>
  <div id="adayazilimDatabase">
    <div class="leftToRight">
      <table id="customerTable">
        <caption class="titleStyle">Customer Table</caption>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Surname</th>
          <th>City</th>
        </tr>
        {% for curCustomer in customerTable %}
        <tr>
          <td>{{ curCustomer.id }}</td>
          <td>{{ curCustomer.name }}</td>
          <td>{{ curCustomer.surname }}</td>
          <td>{{ curCustomer.city }}</td>
        </tr>
        {% endfor %}
      </table>
    </div>
    <div class="leftToRight">
      <table id="basketTable">
        <caption class="titleStyle">Basket Table</caption>
        <tr>
          <th>ID</th>
          <th>CustomerID</th>
        </tr>
        {% for curBasket in basketTable %}
        <tr>
          <td>{{ curBasket.id }}</td>
          <td>{{ curBasket.customer_id }}</td>
        </tr>
        {% endfor %}
      </table>
    </div>
    <div class="leftToRight">
      <table id="basketProductTable">
        <caption class="titleStyle">BasketProduct Table</caption>
        <tr>
          <th>ID</th>
          <th>BasketID</th>
          <th>Cost</th>
          <th>Description</th>
        </tr>
        {% for curBasketProduct in basketProductTable %}
        <tr>
          <td>{{ curBasketProduct.id }}</td>
          <td>{{ curBasketProduct.basket_id }}</td>
          <td>{{ curBasketProduct.cost }} TL</td>
          <td>{{ curBasketProduct.description }}</td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>
</body>

</html>